
node('jenkins-agent-docker-sg2042') {
    stage("checkout scm") {
        cleanWs()
        checkout scm

        load('src/config.groovy')
    }

    def isAnyParams = params.size() != 0
    

    stage("properties") {
        properties([
            parameters(kernel_build_params_keys.collect {
                all_params[it]
            }),
        ])
    }
    
    if(!isAnyParams) {
        sh 'exit 0'
    }

    stage("build") {
        dir("work") {
            timestamps {
                try {
                    // 拉取仓库
                    sh "bash src/git-fetch-in-dir.sh ${FETCH_REF}"

                    // 执行构建脚本
                    sh 'rvck-kernel-build/run.sh'
                    
                    // 更新github状态
                    build wait: false, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: REPO),
                        string(name: 'ISSUE_ID', value: ISSUE_ID),
                        string(name: 'COMMENT_CONTENT', value: 'Kernel build success!'),
                        string(name: 'SET_LABEL', value: 'kernel_build_succeed,lava_checking'),
                    ]
                } catch (err) {
                    
                    build wait: false, job: 'gh_actions', parameters: [
                        string(name: 'REPO', value: REPO),
                        string(name: 'ISSUE_ID', value: ISSUE_ID),
                        string(name: 'COMMENT_CONTENT', value: "Kernel build failed! log:${BUILD_URL}consoleFull"),
                        string(name: 'SET_LABEL', value: 'kernel_build_failed'),
                    ]

                    currentBuild.result = 'FAILURE'
                    throw err
                }
            }
        }
    }

    stage("trigger next") {
        // 触发kunit
        build wait false, job: 'rvck-kunit-test', parameters: kunit_test_params_keys.collect { 
            string(name: it, value: params[it])
        }

        // 触发lava测试
        def lava_trigger_params = lava_trigger_params_keys.findAll {
                        params.containsKey(it)
                    }.collect {
                        string(name: it, value: params[it])
                    }

        lava_trigger_params += [
            string(name: 'rootfs_download_url', value: readFile('work/rootfs_download_url')),
            string(name: 'kernel_download_url', value: readFile('work/kernel_download_url')),
        ]

        echo "lava_trigger_params: ${lava_trigger_params}"
        
        build wait: false, job: 'rvck-lava-trigger', parameters: lava_trigger_params
    }
    
    
}
